Repository cornellius-gp/gpytorch, pull requests merged in 2018-07, with the labels that each got.

#178 Refactoring to consolidate the two methods of defining acquisition fu…
  gpytorch/gpytorchopt/acquisition_functions_functional/__init__.py
  gpytorch/gpytorchopt/acquisition_functions_functional/expected_improvement.py
  gpytorch/gpytorchopt/acquisition_functions_functional/posterior_mean.py
  gpytorch/gpytorchopt/acquisition_functions_functional/probability_of_improvement.py
  gpytorch/gpytorchopt/acquisition_functions_functional/upper_confidence_bound.py
  gpytorch/gpytorchopt/bayesian_optimization_example1_fully_dependent.py
  gpytorch/gpytorchopt/bayesian_optimization_example2_oracle.py
  gpytorch/gpytorchopt/bayesian_optimization_example3_MCMC.py
  gpytorch/gpytorchopt/bayesian_optimization_example4_bom.py
  gpytorch/gpytorchopt/gpytorchopt/acquisition/__init__.py
  gpytorch/gpytorchopt/gpytorchopt/acquisition/functional/__init__.py
  gpytorch/gpytorchopt/gpytorchopt/acquisition/functional/acquisition.py
  gpytorch/gpytorchopt/gpytorchopt/acquisition/functional/knowledge_gradient.py
  gpytorch/gpytorchopt/gpytorchopt/acquisition/modules.py
  gpytorch/gpytorchopt/gpytorchopt/acquisition/strategy/__init__.py
  gpytorch/gpytorchopt/gpytorchopt/acquisition/strategy/acquisition_function_strategy.py
  gpytorch/gpytorchopt/gpytorchopt/acquisition/strategy/discrete_set/__init__.py
  gpytorch/gpytorchopt/gpytorchopt/acquisition/strategy/discrete_set/discrete_set_evaluation_strategy.py
  gpytorch/gpytorchopt/gpytorchopt/acquisition/strategy/discrete_set/discrete_set_random_strategy.py
  gpytorch/gpytorchopt/gpytorchopt/acquisition/strategy/discrete_set/discrete_set_strategy.py
  gpytorch/gpytorchopt/gpytorchopt/acquisition/strategy/discrete_set/ensemble_discrete_set_evaluation_strategy.py
  gpytorch/gpytorchopt/gpytorchopt/acquisition_functions/__init__.py
  gpytorch/gpytorchopt/gpytorchopt/acquisition_functions/acquisition_function.py
  gpytorch/gpytorchopt/gpytorchopt/acquisition_functions/expected_improvement.py
  gpytorch/gpytorchopt/gpytorchopt/acquisition_functions/max_value_entropy_search.py
  gpytorch/gpytorchopt/gpytorchopt/additive/strategy/__init__.py
  gpytorch/gpytorchopt/gpytorchopt/additive/strategy/additive_strategy.py
  gpytorch/gpytorchopt/gpytorchopt/additive/strategy/dim_scan_additive_strategy.py
  gpytorch/gpytorchopt/gpytorchopt/additive/structure_discovery/bag_of_models.py
  gpytorch/gpytorchopt/gpytorchopt/optim/__init__.py
  gpytorch/gpytorchopt/gpytorchopt/optim/random_restart.py
Labels: refactor

#192 Index kernel returns a lazy variable
  gpytorch/kernels/index_kernel.py
  gpytorch/lazy/interpolated_lazy_variable.py
Labels: enhancement

#205 Get priors/variational strategies also for children of torch Modules
  gpytorch/module.py
Labels: bug
