Repository cornellius-gp/gpytorch, pull requests merged in 2018-10, with the labels that each got.

#307 Kernels now take `diag, dim_groups` as arguments (fixes issues with ARD kernels)
  gpytorch/kernels/__init__.py
  gpytorch/kernels/additive_grid_interpolation_kernel.py
  gpytorch/kernels/additive_structure_kernel.py
  gpytorch/kernels/cosine_kernel.py
  gpytorch/kernels/grid_interpolation_kernel.py
  gpytorch/kernels/grid_kernel.py
  gpytorch/kernels/index_kernel.py
  gpytorch/kernels/inducing_point_kernel.py
  gpytorch/kernels/kernel.py
  gpytorch/kernels/lcm_kernel.py
  gpytorch/kernels/linear_kernel.py
  gpytorch/kernels/matern_kernel.py
  gpytorch/kernels/multiplicative_grid_interpolation_kernel.py
  gpytorch/kernels/multitask_kernel.py
  gpytorch/kernels/periodic_kernel.py
  gpytorch/kernels/product_structure_kernel.py
  gpytorch/kernels/rbf_kernel.py
  gpytorch/kernels/scale_kernel.py
  gpytorch/kernels/spectral_mixture_kernel.py
  gpytorch/kernels/white_noise_kernel.py
  gpytorch/lazy/interpolated_lazy_tensor.py
  gpytorch/lazy/lazy_evaluated_kernel_tensor.py
  gpytorch/lazy/sum_batch_lazy_tensor.py
  gpytorch/models/additive_grid_inducing_variational_gp.py
  gpytorch/models/grid_inducing_variational_gp.py
  gpytorch/utils/interpolation.py
  test/examples/test_kissgp_additive_classification.py
  test/examples/test_kissgp_additive_regression.py
  test/examples/test_kissgp_kronecker_product_classification.py
  test/examples/test_kissgp_kronecker_product_regression.py
  test/examples/test_kissgp_multiplicative_regression.py
  test/kernels/test_cosine_kernel.py
  test/kernels/test_linear_kernel.py
  test/kernels/test_matern_kernel.py
  test/kernels/test_rbf_kernel.py
  test/kernels/test_scale_kernel.py
  test/kernels/test_spectral_mixture_kernel.py
  test/utils/test_interpolation.py
Labels: bug, enhancement

#308 Use num_* consistently for attributes (breaking change)
  examples/01_Simple_GP_Regression/Simple_Batch_Mode_GP_Regression.ipynb
  examples/01_Simple_GP_Regression/Simple_GP_Regression.ipynb
  examples/01_Simple_GP_Regression/Simple_GP_Regression_With_LOVE_Fast_Variances_CUDA.ipynb
  examples/01_Simple_GP_Regression/Spectral_Mixture_GP_Regression.ipynb
  examples/02_Simple_GP_Classification/Simple_GP_Classification.ipynb
  examples/03_Multitask_GP_Regression/Hadamard_Multitask_GP_Regression.ipynb
  examples/03_Multitask_GP_Regression/Multitask_GP_Regression.ipynb
  examples/03_Multitask_GP_Regression/Multitask_GP_Regression_Scalable_With_KISSGP.ipynb
  examples/04_Scalable_GP_Regression_1D/KISSGP_Regression_1D.ipynb
  examples/04_Scalable_GP_Regression_1D/KISSGP_Regression_1D_CUDA.ipynb
  examples/04_Scalable_GP_Regression_1D/KISSGP_Regression_1D_With_Stochastic_Variational_Inference.ipynb
  examples/04_Scalable_GP_Regression_1D/KISSGP_Regression_1D_With_Stochastic_Variational_Inference_CUDA.ipynb
  examples/05_Scalable_GP_Regression_Multidimensional/KISSGP_Additive_Regression_CUDA.ipynb
  examples/05_Scalable_GP_Regression_Multidimensional/KISSGP_Deep_Kernel_Regression_CUDA.ipynb
  examples/05_Scalable_GP_Regression_Multidimensional/KISSGP_Deep_Kernel_Regression_With_LOVE_Fast_Variances_CUDA.ipynb
  examples/05_Scalable_GP_Regression_Multidimensional/KISSGP_Deep_Kernel_Regression_With_Stochastic_Variational_Inference_CUDA.ipynb
  examples/05_Scalable_GP_Regression_Multidimensional/KISSGP_Kronecker_Regression.ipynb
  examples/06_Scalable_GP_Classification_1D/KISSGP_Classification_1D.ipynb
  examples/06_Scalable_GP_Classification_1D/KISSGP_Classification_1D_CUDA.ipynb
  examples/07_Scalable_GP_Classification_Multidimensional/KISSGP_Additive_Classification_CUDA.ipynb
  examples/07_Scalable_GP_Classification_Multidimensional/KISSGP_Kronecker_Classification.ipynb
  examples/08_Deep_Kernel_Learning/Deep_Kernel_Learning_DenseNet_CIFAR_Tutorial.ipynb
  gpytorch/beta_features.py
  gpytorch/distributions/multitask_multivariate_normal.py
  gpytorch/functions/__init__.py
  gpytorch/kernels/grid_kernel.py
  gpytorch/kernels/index_kernel.py
  gpytorch/kernels/lcm_kernel.py
  gpytorch/kernels/matern_kernel.py
  gpytorch/kernels/multitask_kernel.py
  gpytorch/kernels/spectral_mixture_kernel.py
  gpytorch/lazy/block_diag_lazy_tensor.py
  gpytorch/lazy/interpolated_lazy_tensor.py
  gpytorch/lazy/kronecker_product_lazy_tensor.py
  gpytorch/lazy/lazy_evaluated_kernel_tensor.py
  gpytorch/lazy/lazy_tensor.py
  gpytorch/likelihoods/multitask_gaussian_likelihood.py
  gpytorch/likelihoods/softmax_likelihood.py
  gpytorch/means/multitask_mean.py
  gpytorch/mlls/variational_marginal_log_likelihood.py
  gpytorch/models/exact_gp.py
  gpytorch/settings.py
  gpytorch/utils/grid.py
  gpytorch/utils/interpolation.py
  gpytorch/utils/linear_cg.py
  gpytorch/utils/sparse.py
  test/examples/test_batch_multitask_gp_regression.py
  test/examples/test_hadamard_multitask_gp_regression.py
  test/examples/test_kissgp_additive_classification.py
  test/examples/test_kissgp_gp_classification.py
  test/examples/test_kissgp_kronecker_product_classification.py
  test/examples/test_kissgp_kronecker_product_regression.py
  test/examples/test_kissgp_variational_regression.py
  test/examples/test_kronecker_multitask_gp_regression.py
  test/examples/test_kronecker_multitask_ski_gp_regression.py
  test/examples/test_lcm_kernel_regression.py
  test/examples/test_simple_gp_classification.py
  test/likelihoods/test_general_multitask_gaussian_likelihood.py
  test/means/test_multitask_mean.py
  test/utils/test_grid.py
Labels: enhancement

#324 Do not squeeze non-batch results in RootDecomposition backward
  gpytorch/functions/_root_decomposition.py
Labels: bug

#322 [WIP] LazyTensors can handle multiple batches
  gpytorch/functions/_inv_quad_log_det.py
  gpytorch/functions/_matmul.py
  gpytorch/functions/_root_decomposition.py
  gpytorch/functions/matmul.py
  gpytorch/lazy/lazy_tensor.py
  gpytorch/lazy/non_lazy_tensor.py
  gpytorch/lazy/root_lazy_tensor.py
  gpytorch/settings.py
  gpytorch/utils/cholesky.py
  gpytorch/utils/eig.py
  gpytorch/utils/lanczos.py
  gpytorch/utils/linear_cg.py
  gpytorch/utils/pivoted_cholesky.py
  gpytorch/utils/stochastic_lq.py
  test/functions/test_inv_matmul.py
  test/functions/test_inv_quad_log_det.py
  test/functions/test_matmul.py
  test/functions/test_root_decomposition.py
  test/lazy/_lazy_tensor_test_case.py
  test/utils/test_lanczos.py
  test/utils/test_pivoted_cholesky.py
Labels: enhancement, refactor

#331 Repeat lazy tensor
  gpytorch/functions/__init__.py
  gpytorch/functions/_inv_quad_log_det.py
  gpytorch/lazy/__init__.py
  gpytorch/lazy/batch_repeat_lazy_tensor.py
  gpytorch/lazy/chol_lazy_tensor.py
  gpytorch/lazy/constant_mul_lazy_tensor.py
  gpytorch/lazy/diag_lazy_tensor.py
  gpytorch/lazy/interpolated_lazy_tensor.py
  gpytorch/lazy/kronecker_product_lazy_tensor.py
  gpytorch/lazy/lazy_tensor.py
  gpytorch/lazy/non_lazy_tensor.py
  gpytorch/lazy/root_lazy_tensor.py
  gpytorch/lazy/sum_lazy_tensor.py
  gpytorch/lazy/toeplitz_lazy_tensor.py
  gpytorch/lazy/zero_lazy_tensor.py
  test/lazy/_lazy_tensor_test_case.py
  test/lazy/test_batch_repeat_lazy_tensor.py
Labels: enhancement

#332 Use custom KL div and log_prob with gpytorch.distributions.MultivarateNormal
  gpytorch/distributions/multitask_multivariate_normal.py
  gpytorch/distributions/multivariate_normal.py
  gpytorch/mlls/exact_marginal_log_likelihood.py
  gpytorch/variational/mvn_variational_strategy.py
  test/distributions/test_multitask_multivariate_normal.py
  test/distributions/test_multivariate_normal.py
Labels: refactor

#333 Throw error if ard_num_dims doesn't match the dimensionality
  gpytorch/kernels/kernel.py
  test/examples/test_kissgp_additive_classification.py
Labels: bug

#338 Fix bug in MatmulLazyTensor derivative return
  gpytorch/lazy/matmul_lazy_tensor.py
Labels: bug
