Repository cornellius-gp/gpytorch, pull requests merged in 2018-09, with the labels that each got.

#283 Proper tensor cloning
  test/functions/test_dsmm.py
  test/functions/test_inv_matmul.py
  test/functions/test_inv_quad_log_det.py
  test/functions/test_matmul.py
  test/functions/test_root_decomposition.py
  test/lazy/test_block_diag_lazy_tensor.py
  test/lazy/test_chol_lazy_tensor.py
  test/lazy/test_constant_mul_lazy_tensor.py
  test/lazy/test_diag_lazy_tensor.py
  test/lazy/test_kronecker_product_lazy_tensor.py
  test/lazy/test_mul_lazy_tensor.py
  test/lazy/test_sum_batch_lazy_tensor.py
Labels: compatibility

#286 [WIP] Derive priors from torch distributions
  gpytorch/functions/_add_diag.py
  gpytorch/kernels/kernel.py
  gpytorch/kernels/linear_kernel.py
  gpytorch/kernels/matern_kernel.py
  gpytorch/kernels/periodic_kernel.py
  gpytorch/kernels/rbf_kernel.py
  gpytorch/likelihoods/gaussian_likelihood.py
  gpytorch/means/constant_mean.py
  gpytorch/module.py
  gpytorch/priors/__init__.py
  gpytorch/priors/_compatibility.py
  gpytorch/priors/gamma_prior.py
  gpytorch/priors/lkj_prior.py
  gpytorch/priors/multivariate_normal_prior.py
  gpytorch/priors/normal_prior.py
  gpytorch/priors/prior.py
  gpytorch/priors/smoothed_box_prior.py
  gpytorch/priors/torch_priors.py
  gpytorch/priors/utils.py
  gpytorch/priors/wishart_prior.py
  test/examples/test_hadamard_multitask_gp_regression.py
  test/examples/test_spectral_mixture_gp_regression.py
  test/priors/__init__.py
  test/priors/test_gamma_prior.py
  test/priors/test_lkj_prior.py
  test/priors/test_multivariate_normal_prior.py
  test/priors/test_normal_prior.py
  test/priors/test_smoothed_box_prior.py
  test/priors/test_utils.py
  test/priors/test_wishart_prior.py
Labels: compatibility, enhancement, refactor

#276 Automatically determine grid bounds for SKI regression
  docs/source/kernels.rst
  gpytorch/kernels/additive_grid_interpolation_kernel.py
  gpytorch/kernels/grid_interpolation_kernel.py
  gpytorch/kernels/grid_kernel.py
  gpytorch/kernels/multiplicative_grid_interpolation_kernel.py
  gpytorch/kernels/spectral_mixture_kernel.py
  gpytorch/utils/__init__.py
  gpytorch/utils/grid.py
  test/examples/test_kissgp_additive_regression.py
  test/examples/test_kissgp_dkl_regression.py
  test/examples/test_kissgp_gp_regression.py
  test/examples/test_kissgp_kronecker_product_regression.py
  test/examples/test_kissgp_multiplicative_regression.py
  test/examples/test_kissgp_white_noise_regression.py
  test/examples/test_kronecker_multitask_ski_gp_regression.py
  test/util/test_grid.py
Labels: enhancement

#290 Implement Wishart and InverseWishart priors
  gpytorch/priors/wishart_prior.py
Labels: enhancement

#295 Fix add diag
  gpytorch/functions/__init__.py
  gpytorch/functions/_add_diag.py
  gpytorch/lazy/lazy_tensor.py
  gpytorch/lazy/zero_lazy_tensor.py
  test/functions/test_add_diag.py
  test/lazy/test_diag_lazy_tensor.py
  test/lazy/test_non_lazy_tensor.py
  test/lazy/test_zero_lazy_tensor.py
Labels: bug

#288 RandomVariable -> gpytorch.distributions.Distribution
  gpytorch/__init__.py
  gpytorch/beta_features.py
  gpytorch/distributions/__init__.py
  gpytorch/distributions/distribution.py
  gpytorch/distributions/multitask_multivariate_normal.py
  gpytorch/distributions/multivariate_normal.py
  gpytorch/kernels/inducing_point_kernel.py
  gpytorch/lazy/interpolated_lazy_tensor.py
  gpytorch/lazy/lazy_tensor.py
  gpytorch/likelihoods/bernoulli_likelihood.py
  gpytorch/likelihoods/gaussian_likelihood.py
  gpytorch/likelihoods/likelihood.py
  gpytorch/likelihoods/multitask_gaussian_likelihood.py
  gpytorch/likelihoods/softmax_likelihood.py
  gpytorch/mlls/exact_marginal_log_likelihood.py
  gpytorch/mlls/marginal_log_likelihood.py
  gpytorch/mlls/variational_marginal_log_likelihood.py
  gpytorch/models/abstract_variational_gp.py
  gpytorch/models/additive_grid_inducing_variational_gp.py
  gpytorch/models/exact_gp.py
  gpytorch/models/grid_inducing_variational_gp.py
  gpytorch/models/variational_gp.py
  gpytorch/module.py
  gpytorch/random_variables/__init__.py
  gpytorch/random_variables/bernoulli_random_variable.py
  gpytorch/random_variables/categorical_random_variable.py
  gpytorch/random_variables/dirichlet_random_variable.py
  gpytorch/random_variables/gaussian_random_variable.py
  gpytorch/random_variables/mixture_random_variable.py
  gpytorch/random_variables/multitask_gaussian_random_variable.py
  gpytorch/random_variables/random_variable.py
  gpytorch/random_variables/samples_random_variable.py
  gpytorch/variational/mvn_variational_strategy.py
  test/distributions/__init__.py
  test/distributions/test_multitask_multivariate_normal.py
  test/distributions/test_multivariate_normal.py
  test/examples/test_batch_gp_regression.py
  test/examples/test_hadamard_multitask_gp_regression.py
  test/examples/test_kissgp_additive_classification.py
  test/examples/test_kissgp_additive_regression.py
  test/examples/test_kissgp_dkl_regression.py
  test/examples/test_kissgp_gp_classification.py
  test/examples/test_kissgp_gp_regression.py
  test/examples/test_kissgp_kronecker_product_classification.py
  test/examples/test_kissgp_kronecker_product_regression.py
  test/examples/test_kissgp_multiplicative_regression.py
  test/examples/test_kissgp_variational_regression.py
  test/examples/test_kissgp_white_noise_regression.py
  test/examples/test_kronecker_multitask_gp_regression.py
  test/examples/test_kronecker_multitask_ski_gp_regression.py
  test/examples/test_sgpr_regression.py
  test/examples/test_simple_gp_classification.py
  test/examples/test_simple_gp_regression.py
  test/examples/test_spectral_mixture_gp_regression.py
  test/examples/test_white_noise_regression.py
  test/likelihoods/test_general_multitask_gaussian_likelihood.py
Labels: enhancement, refactor

#296 Fix LazyTensor.__getitem__
  gpytorch/lazy/block_diag_lazy_tensor.py
  gpytorch/lazy/block_lazy_tensor.py
  gpytorch/lazy/interpolated_lazy_tensor.py
  gpytorch/lazy/lazy_evaluated_kernel_tensor.py
  gpytorch/lazy/lazy_tensor.py
  gpytorch/lazy/zero_lazy_tensor.py
  gpytorch/utils/__init__.py
  test/lazy/test_block_diag_lazy_tensor.py
  test/lazy/test_interpolated_lazy_tensor.py
  test/lazy/test_sum_batch_lazy_tensor.py
  test/lazy/test_toeplitz_lazy_tensor.py
  test/lazy/test_zero_lazy_tensor.py
Labels: bug, unit tests

#304 Reorganize utils
  gpytorch/functions/_dsmm.py
  gpytorch/kernels/additive_grid_interpolation_kernel.py
  gpytorch/kernels/grid_interpolation_kernel.py
  gpytorch/kernels/inducing_point_kernel.py
  gpytorch/kernels/kernel.py
  gpytorch/kernels/lcm_kernel.py
  gpytorch/kernels/linear_kernel.py
  gpytorch/kernels/multiplicative_grid_interpolation_kernel.py
  gpytorch/kernels/white_noise_kernel.py
  gpytorch/lazy/added_diag_lazy_tensor.py
  gpytorch/lazy/interpolated_lazy_tensor.py
  gpytorch/likelihoods/softmax_likelihood.py
  gpytorch/means/constant_mean.py
  gpytorch/means/mean.py
  gpytorch/means/multitask_mean.py
  gpytorch/means/zero_mean.py
  gpytorch/models/grid_inducing_variational_gp.py
  gpytorch/utils/__init__.py
  gpytorch/utils/cholesky.py
  gpytorch/utils/interpolation.py
  gpytorch/utils/sparse.py
  test/_utils.py
  test/distributions/test_multitask_multivariate_normal.py
  test/distributions/test_multivariate_normal.py
  test/functions/test_inv_matmul.py
  test/functions/test_inv_quad_log_det.py
  test/functions/test_matmul.py
  test/functions/test_root_decomposition.py
  test/lazy/test_block_diag_lazy_tensor.py
  test/lazy/test_chol_lazy_tensor.py
  test/lazy/test_diag_lazy_tensor.py
  test/lazy/test_interpolated_lazy_tensor.py
  test/lazy/test_kronecker_product_lazy_tensor.py
  test/lazy/test_matmul_lazy_tensor.py
  test/lazy/test_non_lazy_tensor.py
  test/lazy/test_root_lazy_tensor.py
  test/lazy/test_sum_batch_lazy_tensor.py
  test/lazy/test_toeplitz_lazy_tensor.py
  test/lazy/test_zero_lazy_tensor.py
  test/priors/test_lkj_prior.py
  test/priors/test_smoothed_box_prior.py
  test/util/test_interp.py
  test/utils/__init__.py
  test/utils/test_cholesky.py
  test/utils/test_fft.py
  test/utils/test_grid.py
  test/utils/test_interpolation.py
  test/utils/test_lanczos.py
  test/utils/test_linear_cg.py
  test/utils/test_pivoted_cholesky.py
  test/utils/test_sparse.py
  test/utils/test_toeplitz.py
Labels: refactor
