Repository cornellius-gp/gpytorch, pull requests merged in 2018-11, with the labels that each got.

#343 Fix interpolation boundary with one test point
  gpytorch/utils/interpolation.py
Labels: bug

#342 Fix batch vs standard prediction inconsistencies
  gpytorch/functions/__init__.py
  gpytorch/lazy/interpolated_lazy_tensor.py
  gpytorch/lazy/kronecker_product_lazy_tensor.py
  gpytorch/lazy/lazy_evaluated_kernel_tensor.py
  gpytorch/lazy/lazy_tensor.py
  gpytorch/models/exact_gp.py
Labels: bug

#345 Improve GridKernel
  gpytorch/kernels/grid_interpolation_kernel.py
  gpytorch/kernels/grid_kernel.py
  test/kernels/test_grid_kernel.py
Labels: enhancement, high priority

#352 Various LazyTensor fixes/improvements
  gpytorch/functions/__init__.py
  gpytorch/lazy/batch_repeat_lazy_tensor.py
  gpytorch/lazy/diag_lazy_tensor.py
  test/lazy/test_batch_repeat_lazy_tensor.py
Labels: enhancement

#355 VariationalStrategy now supports batch mode
  examples/04_Scalable_GP_Regression_1D/SVGP_Batch_Regression_1D.ipynb
  examples/04_Scalable_GP_Regression_1D/index.rst
  gpytorch/distributions/multivariate_normal.py
  gpytorch/likelihoods/gaussian_likelihood.py
  gpytorch/mlls/variational_elbo.py
  gpytorch/variational/variational_strategy.py
  test/examples/test_batch_svgp_gp_regression.py
Labels: enhancement

#359 Optional default preconditioner for LazyTensors
  gpytorch/beta_features.py
  gpytorch/lazy/lazy_tensor.py
  gpytorch/lazy/non_lazy_tensor.py
  gpytorch/utils/qr.py
  gpytorch/utils/svd.py
Labels: enhancement

#353 root_decomposition returns a RootLazyTensor
  gpytorch/distributions/multivariate_normal.py
  gpytorch/lazy/batch_repeat_lazy_tensor.py
  gpytorch/lazy/diag_lazy_tensor.py
  gpytorch/lazy/interpolated_lazy_tensor.py
  gpytorch/lazy/lazy_tensor.py
  gpytorch/lazy/mul_lazy_tensor.py
  gpytorch/lazy/root_lazy_tensor.py
  gpytorch/variational/variational_strategy.py
  test/examples/test_batch_svgp_gp_regression.py
  test/functions/test_root_decomposition.py
  test/lazy/_lazy_tensor_test_case.py
  test/lazy/test_root_lazy_tensor.py
  test/lazy/test_toeplitz_lazy_tensor.py
  test/priors/test_multivariate_normal_prior.py
Labels: enhancement

#362 Support for general batch shapes in DiagLazyTensor
  gpytorch/distributions/multivariate_normal.py
  gpytorch/lazy/diag_lazy_tensor.py
  gpytorch/lazy/lazy_tensor.py
  gpytorch/utils/broadcasting.py
Labels: enhancement

#376 Revamp priors
  examples/04_Scalable_GP_Regression_1D/KISSGP_Regression_1D_With_Stochastic_Variational_Inference.ipynb
  examples/07_Scalable_GP_Classification_Multidimensional/KISSGP_Kronecker_Classification.ipynb
  examples/08_Deep_Kernel_Learning/Deep_Kernel_Learning_DenseNet_CIFAR_Tutorial.ipynb
  examples/09_Pyro_Integration/Pyro_SVDKL_GridInterp.ipynb
  gpytorch/kernels/cosine_kernel.py
  gpytorch/kernels/index_kernel.py
  gpytorch/kernels/kernel.py
  gpytorch/kernels/linear_kernel.py
  gpytorch/kernels/matern_kernel.py
  gpytorch/kernels/multitask_kernel.py
  gpytorch/kernels/periodic_kernel.py
  gpytorch/kernels/rbf_kernel.py
  gpytorch/kernels/scale_kernel.py
  gpytorch/kernels/spectral_mixture_kernel.py
  gpytorch/lazy/batch_repeat_lazy_tensor.py
  gpytorch/likelihoods/gaussian_likelihood.py
  gpytorch/likelihoods/multitask_gaussian_likelihood.py
  gpytorch/likelihoods/softmax_likelihood.py
  gpytorch/means/constant_mean.py
  gpytorch/mlls/exact_marginal_log_likelihood.py
  gpytorch/mlls/variational_elbo.py
  gpytorch/models/abstract_variational_gp.py
  gpytorch/module.py
  gpytorch/priors/lkj_prior.py
  gpytorch/priors/prior.py
  gpytorch/priors/smoothed_box_prior.py
  gpytorch/priors/torch_priors.py
  gpytorch/priors/wishart_prior.py
  gpytorch/utils/deprecation.py
  gpytorch/variational/cholesky_variational_distribution.py
  gpytorch/variational/variational_distribution.py
  gpytorch/variational/variational_strategy.py
  test/examples/test_batch_gp_regression.py
  test/examples/test_batch_multitask_gp_regression.py
  test/examples/test_batch_svgp_gp_regression.py
  test/examples/test_grid_gp_regression.py
  test/examples/test_hadamard_multitask_gp_regression.py
  test/examples/test_kissgp_additive_classification.py
  test/examples/test_kissgp_additive_regression.py
  test/examples/test_kissgp_dkl_regression.py
  test/examples/test_kissgp_gp_classification.py
  test/examples/test_kissgp_gp_regression.py
  test/examples/test_kissgp_kronecker_product_classification.py
  test/examples/test_kissgp_kronecker_product_regression.py
  test/examples/test_kissgp_multiplicative_regression.py
  test/examples/test_kissgp_variational_regression.py
  test/examples/test_kissgp_white_noise_regression.py
  test/examples/test_sgpr_regression.py
  test/examples/test_simple_gp_regression.py
  test/examples/test_spectral_mixture_gp_regression.py
  test/examples/test_svgp_gp_regression.py
  test/examples/test_white_noise_regression.py
  test/priors/test_gamma_prior.py
  test/priors/test_lkj_prior.py
  test/priors/test_multivariate_normal_prior.py
  test/priors/test_normal_prior.py
  test/priors/test_smoothed_box_prior.py
Labels: enhancement

#356 Fix test modules
  test/examples/test_batch_multitask_gp_regression.py
  test/examples/test_kissgp_additive_classification.py
  test/examples/test_kissgp_kronecker_product_classification.py
  test/examples/test_kissgp_kronecker_product_regression.py
  test/examples/test_kissgp_multiplicative_regression.py
  test/examples/test_kissgp_variational_regression.py
  test/examples/test_kissgp_white_noise_regression.py
  test/examples/test_kronecker_multitask_gp_regression.py
  test/examples/test_kronecker_multitask_ski_gp_regression.py
  test/examples/test_white_noise_regression.py
  test/functions/test_dsmm.py
  test/functions/test_log_normal_cdf.py
  test/lazy/test_sum_lazy_tensor.py
  test/likelihoods/__init__.py
  test/models/__init__.py
  test/models/_model_test_case.py
  test/models/test_variational_gp.py
  test/utils/test_toeplitz.py
Labels: unit tests

#383 Track inverse parameter transforms
  gpytorch/kernels/cosine_kernel.py
  gpytorch/kernels/index_kernel.py
  gpytorch/kernels/kernel.py
  gpytorch/kernels/matern_kernel.py
  gpytorch/kernels/periodic_kernel.py
  gpytorch/kernels/rbf_kernel.py
  gpytorch/kernels/scale_kernel.py
  gpytorch/kernels/spectral_mixture_kernel.py
  gpytorch/likelihoods/gaussian_likelihood.py
  gpytorch/likelihoods/multitask_gaussian_likelihood.py
  gpytorch/mlls/exact_marginal_log_likelihood.py
  gpytorch/mlls/variational_elbo.py
  gpytorch/module.py
  gpytorch/utils/transforms.py
Labels: enhancement

#389 Deprecate log parameters, use softplus as default transform to ensure positive parameters
  docs/source/conf.py
  gpytorch/kernels/cosine_kernel.py
  gpytorch/kernels/index_kernel.py
  gpytorch/kernels/kernel.py
  gpytorch/kernels/matern_kernel.py
  gpytorch/kernels/periodic_kernel.py
  gpytorch/kernels/rbf_kernel.py
  gpytorch/kernels/scale_kernel.py
  gpytorch/kernels/spectral_mixture_kernel.py
  gpytorch/likelihoods/gaussian_likelihood.py
  gpytorch/likelihoods/multitask_gaussian_likelihood.py
  gpytorch/module.py
  test/examples/test_batch_gp_regression.py
  test/examples/test_grid_gp_regression.py
  test/examples/test_kissgp_dkl_regression.py
  test/examples/test_kissgp_gp_regression.py
  test/examples/test_kissgp_white_noise_regression.py
  test/examples/test_simple_gp_regression.py
  test/examples/test_white_noise_regression.py
  test/kernels/test_additive_kernel.py
  test/kernels/test_rbf_kernel.py
Labels: WIP, enhancement

#337 Heteroskedastic likelihoods and log-noise models
  gpytorch/functions/__init__.py
  gpytorch/kernels/__init__.py
  gpytorch/kernels/white_noise_kernel.py
  gpytorch/lazy/interpolated_lazy_tensor.py
  gpytorch/lazy/lazy_evaluated_kernel_tensor.py
  gpytorch/lazy/lazy_tensor.py
  gpytorch/likelihoods/__init__.py
  gpytorch/likelihoods/gaussian_likelihood.py
  gpytorch/likelihoods/multitask_gaussian_likelihood.py
  gpytorch/likelihoods/noise_models.py
  gpytorch/mlls/exact_marginal_log_likelihood.py
  gpytorch/models/exact_gp.py
  gpytorch/module.py
  gpytorch/settings.py
  gpytorch/utils/grid.py
  gpytorch/utils/log_deprecation.py
  test/examples/test_batch_gp_regression.py
  test/examples/test_batch_multitask_gp_regression.py
  test/examples/test_grid_gp_regression.py
  test/examples/test_kronecker_multitask_ski_gp_regression.py
  test/examples/test_simple_gp_regression.py
  test/examples/test_white_noise_regression.py
  test/likelihoods/test_general_multitask_gaussian_likelihood.py
Labels: WIP, enhancement

#393 Pyro can handle batch models
  gpytorch/lazy/block_diag_lazy_tensor.py
  gpytorch/likelihoods/gaussian_likelihood.py
  gpytorch/models/pyro_variational_gp.py
  gpytorch/variational/cholesky_variational_distribution.py
Labels: enhancement

#394 Remove _batch_get_indices function from LazyTensors
  gpytorch/lazy/batch_repeat_lazy_tensor.py
  gpytorch/lazy/block_diag_lazy_tensor.py
  gpytorch/lazy/block_lazy_tensor.py
  gpytorch/lazy/constant_mul_lazy_tensor.py
  gpytorch/lazy/diag_lazy_tensor.py
  gpytorch/lazy/interpolated_lazy_tensor.py
  gpytorch/lazy/kronecker_product_lazy_tensor.py
  gpytorch/lazy/lazy_evaluated_kernel_tensor.py
  gpytorch/lazy/lazy_tensor.py
  gpytorch/lazy/matmul_lazy_tensor.py
  gpytorch/lazy/mul_lazy_tensor.py
  gpytorch/lazy/non_lazy_tensor.py
  gpytorch/lazy/root_lazy_tensor.py
  gpytorch/lazy/sum_batch_lazy_tensor.py
  gpytorch/lazy/sum_lazy_tensor.py
  gpytorch/lazy/toeplitz_lazy_tensor.py
Labels: refactor

#404 Improve LazyTensor.__getitem__
  gpytorch/lazy/batch_repeat_lazy_tensor.py
  gpytorch/lazy/block_lazy_tensor.py
  gpytorch/lazy/constant_mul_lazy_tensor.py
  gpytorch/lazy/lazy_evaluated_kernel_tensor.py
  gpytorch/lazy/lazy_tensor.py
  gpytorch/lazy/non_lazy_tensor.py
  gpytorch/lazy/sum_lazy_tensor.py
  gpytorch/lazy/zero_lazy_tensor.py
  test/lazy/test_zero_lazy_tensor.py
Labels: refactor

#407 Option to skip LazyTensor.logdet forward pass
  gpytorch/functions/_inv_quad_log_det.py
  gpytorch/settings.py
  test/functions/test_inv_quad_log_det.py
Labels: enhancement
