Repository cornellius-gp/gpytorch, pull requests merged in 2018-08, with the labels that each got.

#218 Better multitask GP interface, more efficient multitask GP predictions
  examples/multitask_gp_regression.ipynb
  examples/multitask_ski_gp_regression.ipynb
  gpytorch/functions/__init__.py
  gpytorch/kernels/__init__.py
  gpytorch/kernels/grid_interpolation_kernel.py
  gpytorch/kernels/index_kernel.py
  gpytorch/kernels/kernel.py
  gpytorch/kernels/multitask_kernel.py
  gpytorch/kernels/white_noise_kernel.py
  gpytorch/lazy/added_diag_lazy_variable.py
  gpytorch/lazy/interpolated_lazy_variable.py
  gpytorch/lazy/lazy_evaluated_kernel_variable.py
  gpytorch/lazy/lazy_variable.py
  gpytorch/likelihoods/__init__.py
  gpytorch/likelihoods/gaussian_likelihood.py
  gpytorch/likelihoods/multitask_gaussian_likelihood.py
  gpytorch/means/__init__.py
  gpytorch/means/multitask_mean.py
  gpytorch/mlls/exact_marginal_log_likelihood.py
  gpytorch/models/exact_gp.py
  gpytorch/random_variables/__init__.py
  gpytorch/random_variables/multitask_gaussian_random_variable.py
  gpytorch/utils/pivoted_cholesky.py
  test/examples/test_batch_gp_regression.py
  test/examples/test_kronecker_multitask_gp_regression.py
  test/examples/test_kronecker_multitask_ski_gp_regression.py
  test/util/test_pivoted_cholesky.py
Labels: enhancement

#221 Speed up Root/Matmul LV get_indices
  gpytorch/lazy/matmul_lazy_variable.py
  gpytorch/lazy/root_lazy_variable.py
  test/lazy/test_matmul_lazy_variable.py
  test/lazy/test_root_lazy_variable.py
Labels: bug

#223 Prior mode for exact GPs
  gpytorch/functions/__init__.py
  gpytorch/models/exact_gp.py
  gpytorch/settings.py
  test/examples/test_multitask_gp_regression.py
  test/examples/test_simple_gp_classification.py
  test/examples/test_simple_gp_regression.py
Labels: enhancement

#225 Add suite of unit tests for WhiteNoiseKernel and ZeroLazyVariable
  gpytorch/kernels/white_noise_kernel.py
  gpytorch/lazy/zero_lazy_variable.py
  test/kernels/test_white_noise_kernel.py
  test/lazy/test_zero_lazy_variable.py
Labels: unit tests

#232 Scale kernel (for getting kernels with outputscales)
  gpytorch/kernels/__init__.py
  gpytorch/kernels/rbf_kernel.py
  gpytorch/kernels/scale_kernel.py
  gpytorch/lazy/constant_mul_lazy_variable.py
  gpytorch/lazy/lazy_evaluated_kernel_variable.py
  gpytorch/lazy/lazy_variable.py
  gpytorch/utils/pivoted_cholesky.py
  test/examples/test_batch_gp_regression.py
  test/examples/test_hadamard_multitask_gp_regression.py
  test/examples/test_kissgp_additive_classification.py
  test/examples/test_kissgp_additive_regression.py
  test/examples/test_kissgp_dkl_regression.py
  test/examples/test_kissgp_gp_classification.py
  test/examples/test_kissgp_gp_regression.py
  test/examples/test_kissgp_kronecker_product_classification.py
  test/examples/test_kissgp_kronecker_product_regression.py
  test/examples/test_kissgp_multiplicative_regression.py
  test/examples/test_kissgp_variational_regression.py
  test/examples/test_kissgp_white_noise_regression.py
  test/examples/test_kronecker_multitask_gp_regression.py
  test/examples/test_kronecker_multitask_ski_gp_regression.py
  test/examples/test_sgpr_regression.py
  test/examples/test_simple_gp_classification.py
  test/examples/test_simple_gp_regression.py
  test/examples/test_spectral_mixture_gp_regression.py
  test/examples/test_white_noise_regression.py
  test/kernels/test_scale_kernel.py
Labels: enhancement
