Repository cornellius-gp/gpytorch, pull requests merged in 2018-03, with the labels that each got.

#83 Add ability to take sum and product of kernels directly, add linear and periodic kernels, create `active_dims`
  gpytorch/kernels/__init__.py
  gpytorch/kernels/additive_grid_interpolation_kernel.py
  gpytorch/kernels/grid_interpolation_kernel.py
  gpytorch/kernels/grid_kernel.py
  gpytorch/kernels/index_kernel.py
  gpytorch/kernels/kernel.py
  gpytorch/kernels/linear_kernel.py
  gpytorch/kernels/matern_kernel.py
  gpytorch/kernels/multiplicative_grid_interpolation_kernel.py
  gpytorch/kernels/periodic_kernel.py
  gpytorch/kernels/rbf_kernel.py
  gpytorch/kernels/spectral_mixture_kernel.py
  test/kernels/test_additive_kernel.py
  test/kernels/test_linear_kernel.py
  test/kernels/test_periodic_kernel.py
  test/kernels/test_rbf_kernel.py
Labels: enhancement

#86 Implement ARD, simplify RBF Kernel
  gpytorch/kernels/grid_interpolation_kernel.py
  gpytorch/kernels/grid_kernel.py
  gpytorch/kernels/index_kernel.py
  gpytorch/kernels/kernel.py
  gpytorch/kernels/matern_kernel.py
  gpytorch/kernels/multiplicative_grid_interpolation_kernel.py
  gpytorch/kernels/periodic_kernel.py
  gpytorch/kernels/rbf_kernel.py
  gpytorch/kernels/spectral_mixture_kernel.py
  test/kernels/test_rbf_kernel.py
Labels: enhancement

#84 Marginal log likelihood (and function factory) refactor
  gpytorch/__init__.py
  gpytorch/lazy/lazy_variable.py
  gpytorch/mlls/exact_marginal_log_likelihood.py
  gpytorch/mlls/variational_marginal_log_likelihood.py
  gpytorch/utils/__init__.py
  gpytorch/utils/function_factory.py
  gpytorch/variational/mvn_variational_strategy.py
  test/lazy/test_constant_mul_lazy_variable.py
  test/lazy/test_sum_lazy_variable.py
  test/util/test_function_factory.py
Labels: refactor

#88 [Codemod] Future imports to improve py2/py3 compatibility
  gpytorch/beta_features.py
  gpytorch/functions/add_diag.py
  gpytorch/functions/dsmm.py
  gpytorch/functions/log_normal_cdf.py
  gpytorch/functions/normal_cdf.py
  gpytorch/kernels/__init__.py
  gpytorch/kernels/additive_grid_interpolation_kernel.py
  gpytorch/lazy/block_diagonal_lazy_variable.py
  gpytorch/lazy/constant_mul_lazy_variable.py
  gpytorch/lazy/diag_lazy_variable.py
  gpytorch/lazy/interpolated_lazy_variable.py
  gpytorch/lazy/kronecker_product_lazy_variable.py
  gpytorch/lazy/lazy_variable.py
  gpytorch/lazy/matmul_lazy_variable.py
  gpytorch/lazy/mul_lazy_variable.py
  gpytorch/lazy/non_lazy_variable.py
  gpytorch/lazy/psd_sum_lazy_variable.py
  gpytorch/lazy/root_lazy_variable.py
  gpytorch/lazy/sum_batch_lazy_variable.py
  gpytorch/lazy/sum_lazy_variable.py
  gpytorch/lazy/toeplitz_lazy_variable.py
  gpytorch/likelihoods/bernoulli_likelihood.py
  gpytorch/likelihoods/gaussian_likelihood.py
  gpytorch/likelihoods/likelihood.py
  gpytorch/likelihoods/softmax_likelihood.py
  gpytorch/means/constant_mean.py
  gpytorch/means/mean.py
  gpytorch/mlls/exact_marginal_log_likelihood.py
  gpytorch/mlls/marginal_log_likelihood.py
  gpytorch/mlls/variational_marginal_log_likelihood.py
  gpytorch/models/abstract_variational_gp.py
  gpytorch/models/additive_grid_inducing_variational_gp.py
  gpytorch/models/exact_gp.py
  gpytorch/models/gp.py
  gpytorch/models/grid_inducing_variational_gp.py
  gpytorch/models/variational_gp.py
  gpytorch/module.py
  gpytorch/random_variables/bernoulli_random_variable.py
  gpytorch/random_variables/categorical_random_variable.py
  gpytorch/random_variables/dirichlet_random_variable.py
  gpytorch/random_variables/gaussian_random_variable.py
  gpytorch/random_variables/mixture_random_variable.py
  gpytorch/random_variables/random_variable.py
  gpytorch/random_variables/samples_random_variable.py
  gpytorch/settings.py
  gpytorch/utils/circulant.py
  gpytorch/utils/fft.py
  gpytorch/utils/function_factory.py
  gpytorch/utils/interpolation.py
  gpytorch/utils/lanczos.py
  gpytorch/utils/linear_cg.py
  gpytorch/utils/sparse.py
  gpytorch/utils/stochastic_lq.py
  gpytorch/utils/toeplitz.py
  gpytorch/variational/mvn_variational_strategy.py
  gpytorch/variational/variational_strategy.py
Labels: compatibility

#92 Fix installation issues with anaconda
  build.py
Labels: bug

#90 [Codemod] Clean up test files
  test/examples/test_kissgp_additive_classification.py
  test/examples/test_kissgp_additive_regression.py
  test/examples/test_kissgp_gp_classification.py
  test/examples/test_kissgp_gp_regression.py
  test/examples/test_kissgp_kronecker_product_classification.py
  test/examples/test_kissgp_kronecker_product_regression.py
  test/examples/test_kissgp_multiplicative_regression.py
  test/examples/test_kissgp_variational_regression.py
  test/examples/test_multitask_gp_regression.py
  test/examples/test_simple_gp_classification.py
  test/examples/test_simple_gp_regression.py
  test/examples/test_spectral_mixture_gp_regression.py
  test/functions/test_add_diag.py
  test/functions/test_dsmm.py
  test/functions/test_log_normal_cdf.py
  test/kernels/test_additive_kernel.py
  test/kernels/test_linear_kernel.py
  test/kernels/test_periodic_kernel.py
  test/lazy/test_block_diagonal_lazy_variable.py
  test/lazy/test_constant_mul_lazy_variable.py
  test/lazy/test_diag_lazy_variable.py
  test/lazy/test_interpolated_lazy_variable.py
  test/lazy/test_kronecker_product_lazy_variable.py
  test/lazy/test_matmul_lazy_variable.py
  test/lazy/test_mul_lazy_variable.py
  test/lazy/test_root_lazy_variable.py
  test/lazy/test_sum_lazy_variable.py
  test/lazy/test_toeplitz_lazy_variable.py
  test/util/test_circulant.py
  test/util/test_cubic_interpolation.py
  test/util/test_fft.py
  test/util/test_function_factory.py
  test/util/test_interp.py
  test/util/test_lanczos.py
  test/util/test_linear_cg.py
  test/util/test_sparse.py
  test/util/test_toeplitz.py
  test/util/test_tridiag.py
Labels: compatibility

#97 Function factory tests work on pytorch 0.3 and 0.4
  test/util/test_function_factory.py
Labels: bug, compatibility

#99 Small fixes
  gpytorch/mlls/variational_marginal_log_likelihood.py
  gpytorch/module.py
  gpytorch/random_variables/categorical_random_variable.py
  gpytorch/random_variables/samples_random_variable.py
Labels: enhancement

#100 Fixes to variational inference
  gpytorch/lazy/__init__.py
  gpytorch/lazy/chol_lazy_variable.py
  gpytorch/lazy/lazy_variable.py
  gpytorch/lazy/sum_lazy_variable.py
  gpytorch/mlls/variational_marginal_log_likelihood.py
  gpytorch/models/abstract_variational_gp.py
  gpytorch/models/grid_inducing_variational_gp.py
  gpytorch/utils/pivoted_cholesky.py
  gpytorch/utils/toeplitz.py
  gpytorch/variational/mvn_variational_strategy.py
  test/lazy/test_chol_lazy_variable.py
Labels: bug, refactor
