Repository cornellius-gp/gpytorch, pull requests merged in 2019-04, with the labels that each got.

#604 [WIP] Efficiency improvements for predictions
  gpytorch/utils/broadcasting.py
Labels: WIP, enhancement

#596 Implement parameter constraints, default noise lower bound
  docs/source/constraints.rst
  docs/source/index.rst
  examples/05_Scalable_GP_Regression_Multidimensional/SVDKL_Regression_GridInterp_CUDA.ipynb
  examples/05_Scalable_GP_Regression_Multidimensional/SVDKL_Regression_SVGP_CUDA.ipynb
  gpytorch/constraints/__init__.py
  gpytorch/constraints/constraints.py
  gpytorch/kernels/cosine_kernel.py
  gpytorch/kernels/index_kernel.py
  gpytorch/kernels/kernel.py
  gpytorch/kernels/linear_kernel.py
  gpytorch/kernels/matern_kernel.py
  gpytorch/kernels/periodic_kernel.py
  gpytorch/kernels/rbf_kernel.py
  gpytorch/kernels/rbf_kernel_grad.py
  gpytorch/kernels/scale_kernel.py
  gpytorch/kernels/spectral_mixture_kernel.py
  gpytorch/likelihoods/gaussian_likelihood.py
  gpytorch/likelihoods/multitask_gaussian_likelihood.py
  gpytorch/likelihoods/noise_models.py
  gpytorch/module.py
  gpytorch/utils/transforms.py
  test/constraints/__init__.py
  test/constraints/test_constraints.py
  test/distributions/test_multivariate_normal.py
  test/examples/test_simple_gp_regression.py
  test/examples/test_svgp_gp_regression.py
  test/examples/test_white_noise_regression.py
  test/examples/test_whitened_svgp_gp_regression.py
  test/functions/test_inv_quad_log_det.py
  test/lazy/_lazy_tensor_test_case.py
Labels: enhancement, refactor

#613 Fix warning in psd_safe_cholesky
  gpytorch/utils/cholesky.py
  test/utils/test_cholesky.py
Labels: bug

#621 Throw error when initializing parameter value to something out of bounds
  gpytorch/constraints/constraints.py
  gpytorch/module.py
  test/kernels/_base_kernel_test_case.py
Labels: bug, high priority

#630 Fix setters for non-tensor initialization values
  gpytorch/kernels/cosine_kernel.py
  gpytorch/kernels/kernel.py
  gpytorch/kernels/linear_kernel.py
  gpytorch/kernels/periodic_kernel.py
  gpytorch/kernels/scale_kernel.py
  gpytorch/kernels/spectral_mixture_kernel.py
  gpytorch/likelihoods/multitask_gaussian_likelihood.py
  gpytorch/likelihoods/noise_models.py
Labels: bug

#636 Add support for fixed noise fantasies
  gpytorch/likelihoods/gaussian_likelihood.py
  gpytorch/likelihoods/likelihood.py
  gpytorch/likelihoods/multitask_gaussian_likelihood.py
  gpytorch/likelihoods/noise_models.py
  gpytorch/models/exact_gp.py
  gpytorch/models/exact_prediction_strategies.py
  test/examples/test_fixed_noise_fanatasy_updates.py
  test/likelihoods/test_gaussian_likelihood.py
Labels: enhancement

#652 Make noise an attribute in FixedGaussianNoise
  gpytorch/likelihoods/noise_models.py
  test/examples/test_kissgp_white_noise_regression.py
Labels: enhancement

#577 [WIP] implement cylindrical kernel
  docs/source/kernels.rst
  gpytorch/kernels/__init__.py
  gpytorch/kernels/cylindrical_kernel.py
  test/kernels/_base_kernel_test_case.py
  test/kernels/test_cylindrical_kernel.py
Labels: enhancement

#669 Variational fixes
  gpytorch/lazy/added_diag_lazy_tensor.py
  gpytorch/likelihoods/likelihood.py
  gpytorch/models/pyro_variational_gp.py
  gpytorch/variational/variational_strategy.py
Labels: bug
