Repository cornellius-gp/gpytorch, pull requests merged in 2019-02, with the labels that each got.

#493 Fix cuda test in test_batch_whitened_svgp_gp_regression
  test/examples/test_batch_whitened_svgp_gp_regression.py
  test/examples/test_whitened_svgp_gp_regression.py
Labels: unit tests

#509 Remove unused __pdist_dist
  gpytorch/kernels/kernel.py
Labels: refactor

#508 Fix autograd bug with preconditioner, default _getitem
  gpytorch/functions/_inv_matmul.py
  gpytorch/functions/_inv_quad_log_det.py
  gpytorch/lazy/lazy_tensor.py
  test/examples/test_grid_gp_regression.py
Labels: bug

#510 Stop cholesky_solve warnings on pytorch-nightly
  examples/01_Simple_GP_Regression/Simple_MultiGPU_GP_Regression.ipynb
  examples/10_GP_Regression_Derivative_Information/Simple_GP_Regression_Derivative_Information_1d.ipynb
  examples/10_GP_Regression_Derivative_Information/Simple_GP_Regression_Derivative_Information_2d.ipynb
  gpytorch/models/exact_prediction_strategies.py
  gpytorch/utils/cholesky.py
  gpytorch/utils/pivoted_cholesky.py
  test/utils/test_cholesky.py
  test/utils/test_linear_cg.py
Labels: compatibility, update_on_next_release

#488 add feature flag to skip posterior covar computation
  gpytorch/models/exact_prediction_strategies.py
  gpytorch/settings.py
  test/examples/test_simple_gp_regression.py
Labels: enhancement

#495 Improve setup.py
  docs/requirements.txt
  gpytorch/__init__.py
  setup.py
Labels: enhancement

#511 Add context manager for selecting min mem cuda device
  test/_utils.py
  test/examples/test_svgp_gp_regression.py
Labels: enhancement, unit tests

#515 Use least_used_cuda_device for all tests
  test/distributions/test_multitask_multivariate_normal.py
  test/distributions/test_multivariate_normal.py
  test/examples/test_batch_svgp_gp_regression.py
  test/examples/test_batch_whitened_svgp_gp_regression.py
  test/examples/test_grid_gp_regression.py
  test/examples/test_kissgp_gp_regression.py
  test/examples/test_kissgp_white_noise_regression.py
  test/examples/test_kronecker_multitask_ski_gp_regression.py
  test/examples/test_model_list_gp_regression.py
  test/examples/test_sgpr_regression.py
  test/examples/test_simple_gp_classification.py
  test/examples/test_simple_gp_regression.py
  test/examples/test_svgp_gp_regression.py
  test/examples/test_white_noise_regression.py
  test/examples/test_whitened_svgp_gp_regression.py
  test/functions/test_matmul.py
  test/functions/test_root_decomposition.py
  test/kernels/test_periodic_kernel.py
  test/kernels/test_spectral_mixture_kernel.py
  test/lazy/_lazy_tensor_test_case.py
  test/lazy/test_cached_cg_lazy_tensor.py
  test/lazy/test_zero_lazy_tensor.py
  test/priors/test_gamma_prior.py
  test/priors/test_lkj_prior.py
  test/priors/test_multivariate_normal_prior.py
  test/priors/test_normal_prior.py
  test/priors/test_smoothed_box_prior.py
  test/utils/test_cholesky.py
  test/utils/test_lanczos.py
  test/utils/test_linear_cg.py
  test/utils/test_pivoted_cholesky.py
  test/utils/test_quadrature.py
Labels: unit tests

#519 Improve speed, stability of woodbury for preconditioner
  gpytorch/lazy/added_diag_lazy_tensor.py
  gpytorch/utils/pivoted_cholesky.py
  gpytorch/utils/woodbury.py
  test/utils/test_pivoted_cholesky.py
Labels: enhancement
