Repository cornellius-gp/gpytorch, pull requests merged in 2019-01, with the labels that each got.

#451 Make "lazify/delazify" helpers, better lazy kernel evaluation
  gpytorch/__init__.py
  gpytorch/distributions/multivariate_normal.py
  gpytorch/functions/__init__.py
  gpytorch/functions/_root_decomposition.py
  gpytorch/kernels/additive_structure_kernel.py
  gpytorch/kernels/grid_kernel.py
  gpytorch/kernels/inducing_point_kernel.py
  gpytorch/kernels/kernel.py
  gpytorch/kernels/multitask_kernel.py
  gpytorch/kernels/product_structure_kernel.py
  gpytorch/kernels/scale_kernel.py
  gpytorch/lazy/__init__.py
  gpytorch/lazy/added_diag_lazy_tensor.py
  gpytorch/lazy/diag_lazy_tensor.py
  gpytorch/lazy/interpolated_lazy_tensor.py
  gpytorch/lazy/kronecker_product_lazy_tensor.py
  gpytorch/lazy/lazy_evaluated_kernel_tensor.py
  gpytorch/lazy/lazy_tensor.py
  gpytorch/lazy/matmul_lazy_tensor.py
  gpytorch/lazy/mul_lazy_tensor.py
  gpytorch/lazy/non_lazy_tensor.py
  gpytorch/lazy/root_lazy_tensor.py
  gpytorch/lazy/sum_lazy_tensor.py
  gpytorch/likelihoods/multitask_gaussian_likelihood.py
  gpytorch/settings.py
  gpytorch/utils/pivoted_cholesky.py
  gpytorch/variational/cholesky_variational_distribution.py
Labels: refactor

#454 Cache solves for fast variational
  gpytorch/distributions/multivariate_normal.py
  gpytorch/functions/__init__.py
  gpytorch/functions/_inv_matmul.py
  gpytorch/functions/_inv_quad_log_det.py
  gpytorch/lazy/__init__.py
  gpytorch/lazy/cached_cg_lazy_tensor.py
  gpytorch/lazy/chol_lazy_tensor.py
  gpytorch/lazy/diag_lazy_tensor.py
  gpytorch/lazy/lazy_tensor.py
  gpytorch/lazy/zero_lazy_tensor.py
  gpytorch/variational/variational_strategy.py
  test/examples/test_batch_svgp_gp_regression.py
  test/examples/test_svgp_gp_regression.py
  test/lazy/_lazy_tensor_test_case.py
  test/lazy/test_cached_cg_lazy_tensor.py
Labels: enhancement

#450 Support for multi-device GPs
  docs/source/conf.py
  docs/source/kernels.rst
  docs/source/lazy.rst
  examples/01_Simple_GP_Regression/Simple_GP_Regression.ipynb
  examples/01_Simple_GP_Regression/Simple_MultiGPU_GP_Regression.ipynb
  examples/01_Simple_GP_Regression/index.rst
  gpytorch/kernels/__init__.py
  gpytorch/kernels/multi_device_kernel.py
  gpytorch/lazy/__init__.py
  gpytorch/lazy/cat_lazy_tensor.py
  gpytorch/lazy/lazy_tensor.py
  test/lazy/_lazy_tensor_test_case.py
  test/lazy/test_cat_lazy_tensor.py
Labels: enhancement

#458 log_det -> logdet (with appropriate deprecation warnings
  docs/source/functions.rst
  gpytorch/__init__.py
  gpytorch/distributions/multivariate_normal.py
  gpytorch/functions/__init__.py
  gpytorch/functions/_inv_matmul.py
  gpytorch/functions/_inv_quad_log_det.py
  gpytorch/lazy/added_diag_lazy_tensor.py
  gpytorch/lazy/batch_repeat_lazy_tensor.py
  gpytorch/lazy/block_diag_lazy_tensor.py
  gpytorch/lazy/cat_lazy_tensor.py
  gpytorch/lazy/chol_lazy_tensor.py
  gpytorch/lazy/diag_lazy_tensor.py
  gpytorch/lazy/lazy_tensor.py
  gpytorch/lazy/zero_lazy_tensor.py
  gpytorch/utils/deprecation.py
  test/functions/test_inv_quad_log_det.py
  test/lazy/_lazy_tensor_test_case.py
  test/lazy/test_cached_cg_lazy_tensor.py
Labels: enhancement

#459 LazyTensors can broadcast matmuls
  gpytorch/functions/_dsmm.py
  gpytorch/functions/_matmul.py
  gpytorch/lazy/constant_mul_lazy_tensor.py
  gpytorch/lazy/interpolated_lazy_tensor.py
  gpytorch/lazy/kronecker_product_lazy_tensor.py
  gpytorch/lazy/mul_lazy_tensor.py
  gpytorch/lazy/toeplitz_lazy_tensor.py
  gpytorch/utils/__init__.py
  gpytorch/utils/batch.py
  gpytorch/utils/interpolation.py
  gpytorch/utils/sparse.py
  gpytorch/utils/toeplitz.py
  test/functions/test_dsmm.py
  test/lazy/_lazy_tensor_test_case.py
  test/lazy/test_batch_repeat_lazy_tensor.py
  test/lazy/test_block_diag_lazy_tensor.py
  test/lazy/test_cached_cg_lazy_tensor.py
  test/lazy/test_cat_lazy_tensor.py
  test/lazy/test_constant_mul_lazy_tensor.py
  test/lazy/test_sum_batch_lazy_tensor.py
  test/utils/test_sparse.py
Labels: enhancement

#466 Smarter root_decomposition for BlockDiagLazyTensor
  gpytorch/lazy/block_diag_lazy_tensor.py
Labels: enhancement

#464 JIT for distance computation, more efficient Matern kernel, JIT scripted linear CG
  gpytorch/kernels/kernel.py
  gpytorch/kernels/rbf_kernel.py
  gpytorch/utils/linear_cg.py
  test/kernels/test_grid_kernel.py
Labels: WIP

#471 Multi-output GP model
  examples/11_ModelList_GP_Regression/ModelList_GP_Regression.ipynb
  examples/11_ModelList_GP_Regression/README.md
  examples/11_ModelList_GP_Regression/index.rst
  gpytorch/likelihoods/__init__.py
  gpytorch/likelihoods/likelihood_list.py
  gpytorch/mlls/__init__.py
  gpytorch/mlls/sum_marginal_log_likelihood.py
  gpytorch/models/__init__.py
  gpytorch/models/model_list.py
  gpytorch/module.py
  test/examples/test_model_list_gp_regression.py
Labels: enhancement
