Repository cornellius-gp/gpytorch, pull requests merged in 2019-03, with the labels that each got.

#544 More CG improvements
  gpytorch/utils/linear_cg.py
  test/utils/test_linear_cg.py
Labels: bug

#545 Fix index for get_base_samples in interleaved MTMVN
  gpytorch/distributions/multitask_multivariate_normal.py
Labels: bug

#547 Fix batch_symeig cuda index issue
  gpytorch/utils/eig.py
Labels: bug

#530 Allow arbitrary batch shapes in MTMVN
  gpytorch/distributions/multitask_multivariate_normal.py
  test/distributions/test_multitask_multivariate_normal.py
Labels: enhancement

#499 Kernel checkpointing
  gpytorch/beta_features.py
  gpytorch/kernels/kernel.py
  gpytorch/lazy/lazy_evaluated_kernel_tensor.py
  gpytorch/lazy/lazy_tensor.py
  gpytorch/lazy/lazy_tensor_representation_tree.py
  gpytorch/lazy/mul_lazy_tensor.py
  gpytorch/models/exact_gp.py
  gpytorch/models/exact_prediction_strategies.py
  gpytorch/utils/cholesky.py
  gpytorch/utils/memoize.py
  gpytorch/utils/pivoted_cholesky.py
  gpytorch/variational/variational_strategy.py
  gpytorch/variational/whitened_variational_strategy.py
  test/examples/test_simple_gp_regression.py
Labels: enhancement

#517 Custom RBF and Matern Functions
  README.md
  gpytorch/functions/__init__.py
  gpytorch/functions/matern_covariance.py
  gpytorch/functions/rbf_covariance.py
  gpytorch/kernels/kernel.py
  gpytorch/kernels/matern_kernel.py
  gpytorch/kernels/rbf_kernel.py
  test/functions/test_matern_covariance.py
  test/functions/test_rbf_covariance.py
Labels: enhancement

#568 Preconditioner tolerance setting
  gpytorch/settings.py
  gpytorch/utils/pivoted_cholesky.py
Labels: enhancement

#569 CG Improvements
  gpytorch/models/exact_gp.py
  gpytorch/settings.py
  gpytorch/utils/linear_cg.py
Labels: enhancement

#492 Arbitrary number of batch dimensions for LazyTensors
  gpytorch/distributions/multitask_multivariate_normal.py
  gpytorch/distributions/multivariate_normal.py
  gpytorch/functions/_root_decomposition.py
  gpytorch/kernels/additive_structure_kernel.py
  gpytorch/kernels/kernel.py
  gpytorch/kernels/product_structure_kernel.py
  gpytorch/kernels/scale_kernel.py
  gpytorch/lazy/batch_repeat_lazy_tensor.py
  gpytorch/lazy/block_diag_lazy_tensor.py
  gpytorch/lazy/block_lazy_tensor.py
  gpytorch/lazy/cached_cg_lazy_tensor.py
  gpytorch/lazy/cat_lazy_tensor.py
  gpytorch/lazy/constant_mul_lazy_tensor.py
  gpytorch/lazy/diag_lazy_tensor.py
  gpytorch/lazy/interpolated_lazy_tensor.py
  gpytorch/lazy/kronecker_product_lazy_tensor.py
  gpytorch/lazy/lazy_evaluated_kernel_tensor.py
  gpytorch/lazy/lazy_tensor.py
  gpytorch/lazy/matmul_lazy_tensor.py
  gpytorch/lazy/mul_lazy_tensor.py
  gpytorch/lazy/non_lazy_tensor.py
  gpytorch/lazy/root_lazy_tensor.py
  gpytorch/lazy/sum_batch_lazy_tensor.py
  gpytorch/lazy/sum_lazy_tensor.py
  gpytorch/lazy/toeplitz_lazy_tensor.py
  gpytorch/lazy/zero_lazy_tensor.py
  gpytorch/likelihoods/multitask_gaussian_likelihood.py
  gpytorch/utils/__init__.py
  gpytorch/utils/batch.py
  gpytorch/utils/broadcasting.py
  gpytorch/utils/getitem.py
  gpytorch/utils/interpolation.py
  gpytorch/utils/sparse.py
  gpytorch/variational/additive_grid_interpolation_variational_strategy.py
  test/lazy/_lazy_tensor_test_case.py
  test/lazy/test_added_diag_lazy_tensor.py
  test/lazy/test_batch_repeat_lazy_tensor.py
  test/lazy/test_block_diag_lazy_tensor.py
  test/lazy/test_cached_cg_lazy_tensor.py
  test/lazy/test_cat_lazy_tensor.py
  test/lazy/test_chol_lazy_tensor.py
  test/lazy/test_constant_mul_lazy_tensor.py
  test/lazy/test_diag_lazy_tensor.py
  test/lazy/test_interpolated_lazy_tensor.py
  test/lazy/test_kronecker_product_lazy_tensor.py
  test/lazy/test_lazy_evaluated_kernel_tensor.py
  test/lazy/test_matmul_lazy_tensor.py
  test/lazy/test_mul_lazy_tensor.py
  test/lazy/test_non_lazy_tensor.py
  test/lazy/test_psd_sum_lazy_tensor.py
  test/lazy/test_root_lazy_tensor.py
  test/lazy/test_sum_batch_lazy_tensor.py
  test/lazy/test_sum_lazy_tensor.py
  test/lazy/test_toeplitz_lazy_tensor.py
  test/lazy/test_zero_lazy_tensor.py
  test/utils/test_getitem.py
Labels: enhancement, refactor

#586 Better Cholesky methods for use in small data regimes and for debugging
  gpytorch/functions/_inv_matmul.py
  gpytorch/functions/_inv_quad.py
  gpytorch/functions/_inv_quad_log_det.py
  gpytorch/functions/_root_decomposition.py
  gpytorch/lazy/batch_repeat_lazy_tensor.py
  gpytorch/lazy/block_diag_lazy_tensor.py
  gpytorch/lazy/cached_cg_lazy_tensor.py
  gpytorch/lazy/chol_lazy_tensor.py
  gpytorch/lazy/diag_lazy_tensor.py
  gpytorch/lazy/lazy_tensor.py
  gpytorch/lazy/mul_lazy_tensor.py
  gpytorch/lazy/root_lazy_tensor.py
  gpytorch/lazy/zero_lazy_tensor.py
  gpytorch/settings.py
  gpytorch/utils/memoize.py
  gpytorch/variational/variational_strategy.py
  gpytorch/variational/whitened_variational_strategy.py
  test/_base_test_case.py
  test/examples/test_svgp_gp_regression.py
  test/examples/test_whitened_svgp_gp_regression.py
  test/functions/test_inv_quad.py
  test/functions/test_inv_quad_log_det.py
  test/lazy/_lazy_tensor_test_case.py
  test/lazy/test_cached_cg_lazy_tensor.py
  test/lazy/test_chol_lazy_tensor.py
  test/lazy/test_diag_lazy_tensor.py
  test/lazy/test_kronecker_product_lazy_tensor.py
  test/lazy/test_mul_lazy_tensor.py
  test/lazy/test_root_lazy_tensor.py
Labels: enhancement, refactor

#591 Change likelihood signature, several Pyro fixes
  examples/02_Simple_GP_Classification/Simple_GP_Classification.ipynb
  examples/06_Scalable_GP_Classification_1D/KISSGP_Classification_1D.ipynb
  examples/07_Scalable_GP_Classification_Multidimensional/KISSGP_Additive_Classification_CUDA.ipynb
  examples/07_Scalable_GP_Classification_Multidimensional/KISSGP_Kronecker_Classification.ipynb
  examples/09_Pyro_Integration/Pyro_Simple_GP_Classification.ipynb
  examples/09_Pyro_Integration/Pyro_Variational_GP_Regression.ipynb
  gpytorch/distributions/__init__.py
  gpytorch/likelihoods/bernoulli_likelihood.py
  gpytorch/likelihoods/gaussian_likelihood.py
  gpytorch/likelihoods/likelihood.py
  gpytorch/likelihoods/likelihood_list.py
  gpytorch/likelihoods/multitask_gaussian_likelihood.py
  gpytorch/likelihoods/softmax_likelihood.py
  gpytorch/mlls/variational_elbo.py
  gpytorch/models/pyro_variational_gp.py
  gpytorch/utils/quadrature.py
  test/examples/test_kissgp_additive_classification.py
  test/examples/test_kissgp_gp_classification.py
  test/examples/test_kissgp_kronecker_product_classification.py
  test/examples/test_simple_gp_classification.py
Labels: breaking change, bug, enhancement

#599 Don't cache prior_dist for VI
  gpytorch/distributions/multivariate_normal.py
  gpytorch/variational/variational_strategy.py
Labels: bug

#601 Don't run preconditioner for cholesky solves
  gpytorch/functions/_inv_matmul.py
  gpytorch/functions/_inv_quad.py
  gpytorch/lazy/cached_cg_lazy_tensor.py
Labels: bug
