Repository cornellius-gp/gpytorch, pull requests merged in 2020-10, with the labels that each got.

#1299 Fix bug in fixed-noise preconditioner
  gpytorch/lazy/added_diag_lazy_tensor.py
  test/examples/test_white_noise_regression.py
Labels: bug

#1312 Fix shape issue for MMVN with broadcasted means
  gpytorch/distributions/multitask_multivariate_normal.py
  test/distributions/test_multitask_multivariate_normal.py
Labels: bug, high priority, multitask

#1307 Explicitly cast constraint bounds to float
  gpytorch/constraints/constraints.py
Labels: high priority

#1319 Bypass keops for small/rectangular kernels
  gpytorch/kernels/keops/matern_kernel.py
  gpytorch/kernels/keops/rbf_kernel.py
Labels: enhancement, high priority
