Repository cornellius-gp/gpytorch, pull requests merged in 2020-08, with the labels that each got.

#1102 Add TriangularLazyTensor
  gpytorch/functions/_inv_matmul.py
  gpytorch/functions/_inv_quad.py
  gpytorch/lazy/__init__.py
  gpytorch/lazy/batch_repeat_lazy_tensor.py
  gpytorch/lazy/block_diag_lazy_tensor.py
  gpytorch/lazy/block_interleaved_lazy_tensor.py
  gpytorch/lazy/cached_cg_lazy_tensor.py
  gpytorch/lazy/chol_lazy_tensor.py
  gpytorch/lazy/diag_lazy_tensor.py
  gpytorch/lazy/kronecker_product_lazy_tensor.py
  gpytorch/lazy/lazy_tensor.py
  gpytorch/lazy/non_lazy_tensor.py
  gpytorch/lazy/root_lazy_tensor.py
  gpytorch/lazy/triangular_lazy_tensor.py
  gpytorch/models/exact_prediction_strategies.py
  gpytorch/priors/lkj_prior.py
  gpytorch/test/lazy_tensor_test_case.py
  gpytorch/utils/cholesky.py
  gpytorch/utils/errors.py
  gpytorch/utils/memoize.py
  gpytorch/variational/_variational_strategy.py
  gpytorch/variational/batch_decoupled_variational_strategy.py
  gpytorch/variational/cholesky_variational_distribution.py
  gpytorch/variational/orthogonally_decoupled_variational_strategy.py
  gpytorch/variational/unwhitened_variational_strategy.py
  gpytorch/variational/variational_strategy.py
  gpytorch/variational/whitened_variational_strategy.py
  test/lazy/test_chol_lazy_tensor.py
  test/lazy/test_interpolated_lazy_tensor.py
  test/lazy/test_kronecker_product_added_diag_lazy_tensor.py
Labels: enhancement, refactor

#1238 Some small fixes to the low-level Pyro interface
  examples/07_Pyro_Integration/Cox_Process_Example.ipynb
  gpytorch/models/pyro/_pyro_mixin.py
  test/examples/test_lmc_svgp_regression.py
Labels: bug

#1234 add smoke tests to two notebooks where it was missing
  examples/01_Exact_GPs/Spectral_Mixture_GP_Regression.ipynb
  examples/02_Scalable_Exact_GPs/Exact_GP_Posterior_Sampling_with_CIQ.ipynb
  gpytorch/utils/cholesky.py
Labels: unit tests

#1237 Make sure MVN variances are positive (raise warning if not)
  gpytorch/distributions/multivariate_normal.py
  gpytorch/settings.py
  test/distributions/test_multitask_multivariate_normal.py
Labels: stability

#1258 Natural gradient descent v3
  docs/source/index.rst
  docs/source/optim.rst
  docs/source/variational.rst
  examples/04_Variational_and_Approximate_GPs/Natural_Gradient_Descent.ipynb
  examples/04_Variational_and_Approximate_GPs/index.rst
  gpytorch/__init__.py
  gpytorch/lazy/chol_lazy_tensor.py
  gpytorch/lazy/lazy_tensor.py
  gpytorch/models/pyro/_pyro_mixin.py
  gpytorch/module.py
  gpytorch/optim/__init__.py
  gpytorch/optim/ngd.py
  gpytorch/variational/__init__.py
  gpytorch/variational/_variational_distribution.py
  gpytorch/variational/cholesky_variational_distribution.py
  gpytorch/variational/delta_variational_distribution.py
  gpytorch/variational/mean_field_variational_distribution.py
  gpytorch/variational/natural_variational_distribution.py
  gpytorch/variational/tril_natural_variational_distribution.py
  gpytorch/variational/whitened_variational_strategy.py
  test/optim/__init__.py
  test/optim/test_ngd.py
  test/variational/test_natural_variational_distribution.py
Labels: enhancement, variational
