Repository cornellius-gp/gpytorch, pull requests merged in 2020-02, with the labels that each got.

#1036 Fix batch preconditioner
  gpytorch/lazy/added_diag_lazy_tensor.py
Labels: batch mode, enhancement

#1058 Fix issue in pytorch#master with tril_indices
  gpytorch/likelihoods/multitask_gaussian_likelihood.py
Labels: bug

#1057 Orthogonally decoupled variational strategy
  docs/source/variational.rst
  examples/04_Variational_and_Approximate_GPs/Modifying_the_variational_strategy_and_distribution.ipynb
  examples/04_Variational_and_Approximate_GPs/index.rst
  gpytorch/variational/__init__.py
  gpytorch/variational/orthogonally_decoupled_variational_strategy.py
  test/examples/test_decoupled_svgp_regression.py
  test/variational/test_orthogonally_decoupled_variational_strategy.py
Labels: enhancement, variational
